name: Legacy Deploy (net472)

on:
  workflow_dispatch:
  workflow_run:
    branches: [legacy]
    workflows: [Build-Test]
    types:
      - completed

concurrency:
  group: legacydeploy
  cancel-in-progress: true

env:
  CUO_OUTPUT_PATH: '../../bin/dist'
  CUO_PROJECT_PATH: "src/ClassicUO.Client/ClassicUO.Client.csproj"
  CUO_ZIP_NAME: "TazUO.zip"

  DOTNET_NOLOGO: false
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  NUGET_XMLDOC_MODE: skip

jobs:
  build:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: windows-latest
    strategy:
      max-parallel: 1

    steps:
      - name: Checkout legacy
        uses: actions/checkout@v4
        with:
          ref: "legacy"
          submodules: recursive

      - name: Extract Version
        shell: bash
        run: |
          export LC_ALL=C.UTF-8
          echo "VERSION=$(grep -oP '<AssemblyVersion>\K\d+\.\d+\.\d+' src/ClassicUO.Client/ClassicUO.Client.csproj)" >> $GITHUB_ENV

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish (net472)
        run: dotnet publish ${{ env.CUO_PROJECT_PATH }} -c Release -o ${{ env.CUO_OUTPUT_PATH }} -p:IS_DEV_BUILD=true

      - name: Create package
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: ${{ env.CUO_OUTPUT_PATH }}
          filename: ${{ env.CUO_ZIP_NAME }}
          exclusions: '*.zip'

      - name: Upload build artifact (zip)
        uses: actions/upload-artifact@v4
        with:
          name: TazUO-legacy-net472-v${{ env.VERSION }}
          path: ${{ env.CUO_OUTPUT_PATH }}/${{ env.CUO_ZIP_NAME }}
          if-no-files-found: error
